.core-defs:
  variables:
    JNI_PATH: .
    CORENAME: citra
    API_LEVEL: 21
    BASE_CORE_ARGS: -DENABLE_TESTS=OFF -DENABLE_DEDICATED_ROOM=OFF -DENABLE_SDL2=OFF -DENABLE_QT=OFF -DENABLE_WEB_SERVICE=OFF -DENABLE_SCRIPTING=OFF -DENABLE_OPENAL=OFF -DENABLE_LIBUSB=OFF -DCITRA_ENABLE_BUNDLE_TARGET=OFF -DCITRA_WARNINGS_AS_ERRORS=OFF
    CORE_ARGS: ${BASE_CORE_ARGS}

variables:
  STATIC_RETROARCH_BRANCH: master
  GIT_SUBMODULE_STRATEGY: recursive

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ##############################  ##
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  ################################## CELLULAR ##############################  ##
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  ################################## CONSOLES ##############################  ##

  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-cmake-x86_64
  variables:
    EXTRA_PATH: bin/Release

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-cmake-x86_64
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:backports
  variables:
    CORE_ARGS: ${BASE_CORE_ARGS} -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11

################################### CELLULAR #################################
# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs
  variables:
    ANDROID_NDK_VERSION: 26.2.11394342
    NDK_ROOT: /android-sdk-linux/ndk/$ANDROID_NDK_VERSION

################################### CONSOLES #################################

# libretro-build-libnx-aarch64:
#   extends:
#     - .core-defs
#     - .libretro-libnx-static-retroarch-master
